# 应用服务 WEB 访问端口
server.port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/senery
    username: root
    password: 25gn3umb
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
mybatis.type-aliases-package: com.xpu.sceneryview.entity
mybatis:
  configuration:
    map-underscore-to-camel-case: false

start: /webhdfs/v1/

end: ?op=OPEN

base-img-url: http://server:9870
