# 应用服务 WEB 访问端口
server.port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/senery
    username: root
    password: 25gn3umb
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
mybatis.type-aliases-package: com.xpu.sceneryview.entity
mybatis:
  configuration:
    map-underscore-to-camel-case: false

# 是否使用HDFS的数据
hdfs-img: false
hdfs-base-url: http://server:9870
start: /webhdfs/v1/
end: ?op=OPEN
# 使用springboot的路径，最后必须带/
springboot-img-url: http://localhost:8080/

# 是否使用HDFS的VR图,目前没有用
hdfs-vr-img: false

# 是否是服务器，python脚本环境不同
server: false

# 当前jar包路径
jar:


# python脚本需要
scripts: D:\Test\Java\scenery-view\src\main\resources\scripts\wordcloudtest.py
# 停用词位置
stop-words: D:\Test\Java\scenery-view\src\main\resources\scripts\cn_stopwords.txt
# 字体位置
font-path: msyh.ttc
# 生成的词云图位置
wordcloud-path: D:\Test\Java\scenery-view\src\main\resources\static\wordcloud\word_cloud.jpg
